### PR TITLE
Fix path for csv/fit log files

### PR DESCRIPTION
**Pull request by Ptosiek**
Previous PR broke the csv/fit output files (they were not put under the log folder anymore).
So this fixes that.
I also took on adding tests for the logger and I found that the logic to resolve to write_log_python was broken because crc16 was not imported in that case, hence the changes there.

Note that the Cython test is not passing (I'm getting "file write error"). But, is it supposed to work? (You said you run the app with Cython in your case). If yes I will have a look further before merge.

### CODE REVIEW

**Comment by hishizuka** [comment]
Hi @Ptosiek ,
The c++ code needs the following modifications.

modules/logger/cython/logger_fit_c.cpp L617
- (-) sprintf(filename, "%s%s", cfg.G_LOG_DIR, startdate_str);
- (+) sprintf(filename, "%s/%s", cfg.G_LOG_DIR, startdate_str);

Since there is also a fix for the SHARP display in the previous PR, would you like me to fix the source once and for all at this time?

**Comment by Ptosiek** [comment]
I actually did that modification but didn't push yet because I have other issues :)

1. The file name is not the same if we are using cython:
csv/python: 20230928223913
cython: 20230928233913
so some tz mangling.
2. If i change G_LOG_DIR to "tests" for example, the tests pass and files are created but I have:
corrupted size vs. prev_size
Aborted (core dumped)
at the end of execution
3. Fit files are not the same depending on how they are generated
diff tests/20230928233913.fit tests/20230928223913.fit 
Binary files tests/20230928233913.fit and tests/20230928223913.fit differ

**Comment by hishizuka** [comment]
Hi @Ptosiek ,

1. I did not see the difference (mac OS/Raspberry Pi). if you send me the log.db, I will check here too.
2. I did not see the error, too.
3. This is a known issue and the cause is not known, but I don't care as it is the same when uploaded to strava.

**Comment by hishizuka** [comment]
Hi @Ptosiek ,
1. First, do you live in a 2 hour time difference from UTC?  I live in Japan, which does not have daylight saving time, so it is unimplemented, but I think that is a daylight saving time consideration or not. What is the daylight saving time at the time of the log start?
2. I ran tests/tests_logger.py in the fix-loggers-path-output branch of your repository and still could not reproduce it. I changed G_LOG_DIR to "tests" and run one test per run (test_write_log/test_write_log_cython/test_write_log_python) However, we got an import error in python3 tests/tests_logger.py, so we moved it to the top directory and run it in python3 tests_logger.py.
3. Your question gave me a clue. I will decode the fit soon and look for differences.

**Comment by hishizuka** [comment]
There seems to be a daylight saving time bug in the filenames output by cython, I'll fix it in October.

**Comment by hishizuka** [comment]
Hi @Ptosiek ,
I fixed the bug, give it a try.
Other bugs fixed in the latest commit.

**Comment by hishizuka** [comment]
`3. Fit files are not the same depending on how they are generated`
Perhaps the two files now match.

**Comment by Ptosiek** [comment]
Hi @hishizuka,

Yes living in CE(S)T hence daylight saving time is a thing here. The time manipulations are not safe the way they are done but a bug happening is very unlikely here.
Actually I started a bigger refactoring of the loggers, though, your fixes work. e.g.: points 1. and 3 are fixed :+1: 
So this refactoring can probably wait (the idea is to do the time manipulation in python only and have the time/filename as inputs of loggers. This also allows to decouple the code from the config object).
 
I still have point 2 happening when I change the output dir. I don't think it's urgent to fix. Will just open an issue so it's tracked. Getting:
free(): invalid pointer
Aborted (core dumped)

P.S: to run the test, you can do `python -m unittest tests.test_logger` no need to move the file.

**Comment by hishizuka** [comment]
Hi @Ptosiek ,
It's OK. This is a good opportunity to reconsider the halfway function.

**Pull request merged**
