### PR TITLE
Fix for gb

### PR DESCRIPTION
**Pull request by Ptosiek**
Hey,
I have simplified the code for resuming GB:
1. Trying to have all code in gb related part (not sure why you put this along with thingsboard)
2. Handling resuming of GPS data on in a different way (not using a 5s timeout but waiting for GB to connect first).
Honestly the GB connection ain't working very good on my side (it's hardly ever reconnecting) so I can't really tell if it's what you want ?

On a different note, I don't really understand the usage/benefit of the usage of these settings.pickle. What makes that some settings are in there or not and why some as preversed only on crash ?

### CODE REVIEW

**Review by hishizuka — APPROVED** [review]

**Comment by hishizuka** [comment]
Hi @Ptosiek ,
thank you for rewriting!

It is much smarter than my code. The GB resume with GPS worked fine.
After receiving the "is_gps_active" message, the GPS is activated, which is great. I had set the timing for establishing the connection at a reasonable 5 seconds. 
It seems that `call_with_delay` is also a technique for delayed activation.

> On a different note, I don't really understand the usage/benefit of the usage of these settings.pickle. What makes that some settings are in there or not and why some as preversed only on crash ?

Yes, settings.pickle is a workaround for crashes, which sometimes occur as long as the Raspberry Pi is connected to the mobile battery via USB. The program is killed and the Raspberry Pi is restarted. A custom HAT board with JST battery connectors would eliminate the need for this feature. It is one of my goals to build this in the future.

What I would like to achieve is the following.

1. Save the values to keep during one ride
  - `G_MANUAL_STATUS`: press START button to resume recording immediately
  - `ant+~`: Obtain incremental total (distance, work) during shutdown
  - `sealevel_pa`, `sealevel_temp`: If set, recalibrate to avoid elevation shift
  - `G_BT_USE_ADDRESS`, `G_THINGSBOARD_API_STATUS`, `AUTO_UPLOAD_VIA_BT`: resume for ThingBoard upload.
  - `GB`, `GB_gps`: Added as one of the sources of GPS acquisition.
2. Value to be kept during startup (until manual poweroff operation)
  - `mag_min`, `mag_max`: Calibration value of the magnetic sensor. They are difficult to handle because they sometimes have abnormal values due to environmental causes. 1 might be good.
3. What was good in setting.conf
  - `garmin_session`: This is user information.

Some of the rules and implementation are out of sync. I will fix it soon.

**Comment by Ptosiek** [comment]
Thanks for the detailed explanation!
I let you do the out-of-sync fixes then.

The settings/conf/settings.pickle is a bit misleading. 
I understand that it's handy to have all of them visible in one place, 
but then it's unclear what should/can be configured or not. 

I would propose the following:
1. Identify clearly what are constants and what are settings (and in them identify what are application settings and user settings)
-move constants where they belong 
(for example G_COROUTINE_SEM => should just be a const in network file)
-move real settings in settings.py directly and import them directly (no need to stuff them under a singleton as it's making harder to test the code)
(for example: (G_)LOG_ALTITUDE_FROM_DATA_SOURCE = False in settings.py, where it's needed just have: 
from modules import settings and use `settings.LOG_ALTITUDE_FROM_DATA_SOURCE`)
2. config should just be 'app'
3. I would move out the handling of 'settings.pickle' from settings.py and change it to 'state' as it represents the app state a time t.

What do you think?

**Comment by hishizuka** [comment]
Hi @Ptosiek ,
thank you for your propose.

I generally agree, as the config(G_~) has become too large.

> config should just be 'app'

What do you mean by this?

**Comment by Ptosiek** [comment]
Trying to find a different name than config, since config/settings are very similar. But app is problematic because it's also the qt app... have to think this through

**Pull request merged**
