### PR TITLE
Use logging module

### PR DESCRIPTION
**Pull request by Ptosiek**
Use a CustomRotatingHandler that mimics the previous behavior (a new file on each start, no rotation during lifetime of run) with some (small)l changes:
1. The filename of backup log file is based on last modification time on the file (~so shutting down the software)
2. Backup older than 30 days will be automatically removed
3. Date and time are added to each log record in the log file (not on console)

Fix scripts as log are handled/rotated in python now.

I removed the extra spaces in some prints, like print("    tota...), but we can add them back. (But the line is long already with date+time on a small screen)

### CODE REVIEW

**Comment by hishizuka** [comment]
Hi @Ptosiek ,
Thanks for the many PRs each day. I learn a lot.
I have decided on the following requirements for the log, can they be achieved?

1. Capture standard error output.

2. Output standard error output and standard output to the same file.
   The program still has a few unexpected errors and stops, and I want to follow them serially in a single log file.

**Comment by Ptosiek** [comment]
Hi,
Yes can easily be done, a bit of juggling with new lines is required.

I think its a matter of taste, but there are two possible outputs (though the second is more correct in my opinion)

1. One log line for each line
2023-09-21 09:11:19,371 ERROR Task exception was never retrieved
2023-09-21 09:11:19,371 ERROR future: <redacted>
2023-09-21 09:11:19,371 ERROR Traceback (most recent call last):
2023-09-21 09:11:19,372 ERROR   File ".../sensor_core.py", line 454, in integrate
2023-09-21 09:11:19,372 ERROR     self.values["integrated"]["altitude_gps_graph"][-1] = v["GPS"]["alt"]
2023-09-21 09:11:19,372 ERROR KeyError: 'alt'

in case of stdout, say if you have print("something\nsomething else"):

2023-09-21 09:31:15,794 INFO something
2023-09-21 09:31:15,794 INFO something else


2. One line per event (so only the last \n is respected), then output will be:

2023-09-21 09:32:37,517 INFO total : 0.194 sec
2023-09-21 09:32:38,264 ERROR Task exception was never retrieved
future: <redacted>
Traceback (most recent call last):
  File ".../sensor_core.py", line 454, in integrate
    self.values["integrated"]["altitude_gps_graph"][-1] = v["GPS"]["alt"]
KeyError: 'alt'


2023-09-21 09:32:36,674 INFO Qt version: 5.15.2
2023-09-21 09:32:36,709 INFO something
something else

(we can have stdout and sterr configured independently also)

Any preference ?

**Comment by hishizuka** [comment]
Hi @Ptosiek ,
Thanks for the suggestion. My opinion is 2, too.

**Comment by Ptosiek** [comment]
Actually the trick with breaklines is not working everywhere, I found out that later in the program strings can be sent with ending \n to stdout. So we have to go with 1 to have consistent logs.

For stdout there's a small issue because of that code at the beginning of sensor_ant

```
_SENSOR_ANT = False
f = open(os.devnull, "w")
sys.stdout = f
try:
    from ant.easy.node import Node
    from ant.base.driver import find_driver

    # device test
    _driver = find_driver()
    _SENSOR_ANT = True
except ImportError:
    pass
f.close()
sys.stdout = sys.__stdout__
if _SENSOR_ANT:
    app_logger.info("ANT")
    ```
    
e.g. having sys.stdout set to open(os.devnull, "w"). I can easliy solbe it but I wonder if this is still necessary ?

**Comment by hishizuka** [comment]
Hi @Ptosiek ,
Sorry, I tried to try the program and the program is broken.
log/log.db is plain text(debug.txt) at first startup.

Traceback (most recent call last):
  File "/home/pi/pizero_bikecomputer/modules/config.py", line 861, in delay_init
    self.logger.delay_init()
  File "/home/pi/pizero_bikecomputer/modules/logger_core.py", line 125, in delay_init
    self.init_db()
  File "/home/pi/pizero_bikecomputer/modules/logger_core.py", line 260, in init_db
    self.cur.execute(
sqlite3.DatabaseError: file is not a database

**Comment by hishizuka** [comment]
`having sys.stdout set to open(os.devnull, "w"). I can easliy solbe it but I wonder if this is still necessary ?`

This code can be erased.
Instead, can libusb messages output by openant be filtered out?

**Comment by Ptosiek** [comment]
> elf.cur.execute(

1. I can't reproduce your issue. What text do you have exactly in log.db ? I can't see where in the changes it would write in this file

2. I've kept the mangling of stdout for that (cf last commit). Will have a look at that in a different PR then

**Comment by hishizuka** [comment]
Hi @Ptosiek ,
I finally found the cause of the programs not running.

modules/config.py L718
- (-) `self.G_LOG_DEBUG_FILE = os.path.join(self.G_INSTALL_PATH, self.G_LOG_DB)`
- (+) `self.G_LOG_DEBUG_FILE = os.path.join(self.G_INSTALL_PATH, self.G_LOG_DEBUG_FILE)`

**Pull request merged**
