### PR TITLE
Add components

### PR DESCRIPTION
**Pull request by Ptosiek**
1. move qt constants where they belong
2. drop non-used code (pyqt_graph_debug.py)
3. improve/use inheritance
4. less self
5. simplify set_back index code. The back component is always set on changing page.
6. fix mutable button (renamed to buttons)
7. add icons, move logos (on svg per icon, color can dynamically be set if needed)
8. add keys for headless mode
9. fix the focus code ( the custom delete_focus part)

### CODE REVIEW

**Comment by hishizuka** [comment]
Hi @Ptosiek ,
I have found a few bugs in the fixes so far, so please wait a bit.

**Comment by hishizuka** [comment]
I closed the PR by mistake. It has been opened again.
Sorry if you got a useless notification.

**Comment by Ptosiek** [comment]
No worries about the notifications.
Sorry for the bugs, you can just drop the list there and I can fix them.

```
By the way, do you know how to dynamically invert svg colors?
I want to invert the colors of some icons when highlighted in a menu (black background color).
```
I have an idea how to do it (I tested locally), but it will depends on the focus and I think this part has a bug, no ? :)
Let's fix what you saw first and then we will tackle that

**Comment by hishizuka** [comment]
Hi @Ptosiek ,
thanks for the many corrections. I think my code was hard to understand.
Please fix these codes if possible. If it takes much effort, I will fix them.

modules/_pyqt.py 
Need variables for QtCore.Qt.Key_Backtab and QtCore.Qt.Key_Tab. Replace in press_shift_tab and press_tab of modules/gui_pyqt.py.

modules/pyqt/menu/pyqt_course_menu_widget.py L93
obexd command requires absolute path.
- (-) self.config.G_COURSE_DIR,
- (+) os.path.abspath(self.config.G_COURSE_DIR),

modules/pyqt/menu/pyqt_course_menu_widget.py L137, L166 L168
add os.path.join

modules/pyqt/menu/pyqt_course_menu_widget.py L372
If "name" is used, the file name to be retrieved from Ride with gps is wrong.
- (-) self.list_id = course_info["name"]
- (+) self.list_id = course_info["id"]

**Comment by Ptosiek** [comment]
I hope I made it a bit easier :sweat_smile: 
I will have a look at it later today I hope. I think there's still another problem with the focus (I saw your answer on the other thread, i think it will still need some corrections later).
1. Since I don't have access to RWGPS API (and haven't found documentation), could you share an example response? Will be easier to test and fix.
2. Not related but you recently fixed GadgetBridge to handle base64. When is this happening? (/can you share also some example data). Because I've modified this code in another branch (and have merge conflicts) but i never encountered that case

**Comment by hishizuka** [comment]
Hi @Ptosiek ,

1. Sorry for the poor documentation, but I added how to create an API for RWGPS. It takes 3 minutes.
2. This has recently changed GadgetBridge to send messages via BLE and base64 encode the message part(body). This happens anytime a notification comes to the Android smartphone. (since all notifications are forwarded). I will try to create the test unit that you have shared with me.

Also, I fixed an import error in sensor_ant.py when ANT+ is available but the ANT+ dongle is not attached.

**Comment by hishizuka** [comment]
Hi @Ptosiek ,
I couldn't make the test code work, so I'll share GB's sample data.

```
GB({"t":"notify","id":1696719609,"src":"APP name","title”:”Sender Name","subject":"","body":"Abcdabcdabcdabcdabcdanvd","sender":""})
GB({"t":"notify","id":1696719611,"src":"APP name","title":"Sender Name","subject":"","body":atob("44GI44Gj44GV44Gu44G744GE44GVCuOBguOBquOBu+OCjOOAgOOBveOCkwrjgZnjgZPjgaPjgbfjgIDjgZnjgZPjgaPjgbcK44GC44Gq44G744KM44CA44G944KT"),"sender":""})
```

If you encode the body of the second message, you will see some spell-like Japanese, but don't worry about it.

**Comment by Ptosiek** [comment]
Thanks, this will come in the GPS branch refactor. (It depends on the bluetooth branch for now though)

**Pull request merged**
