### PR TITLE
Add Option for Horizontal or Vertical Display Orientation

### PR DESCRIPTION
**Pull request by McJackson164**
Hi!
This pull request introduces a new feature that allows users to choose between a horizontal or vertical display orientation.

#### Config:
- Added a new setting/config property: `G_DISPLAY_ORIENTATION`.
- Added new yaml property: `LAYOUT_VERTICAL`.
    - Using this property, you can provide one layout for each display orientation.

#### UI Adjustments:
- Modified the layout logic to dynamically adjust based on the selected orientation.

#### Refactor:
- Change the `clear_button` label from `x` to `Del`

### CODE REVIEW

**Comment by hishizuka** [comment]
Please tell me about your environment in which you developed this.

**Comment by McJackson164** [comment]
On Windows, so no display yet. My components arrive next week (i.a. ST7789 Display). I will implement the display rotation logic as soon as the components arrive.

**Comment by hishizuka** [comment]
Please PR the code with the actual display in motion.
It probably won't work in my environment and will need additional modifications.

ST7789, like PiTFT, will no longer be supported.

**Comment by McJackson164** [comment]
Why won't ST7789 displays be supported anymore?

I got it working, but i have to clean the code before i push the changes.
WhatsApp Bild 2024-05-31 um 13 40 32_4e75891f

FYI: I'm using the adafruit_rgb_display library to add another ST7789 implementation. I faced problems using the already added implementation of the ST7789 display when trying to rotate the image.

**Comment by hishizuka** [comment]
Great!

Under what situations would you use this device?
If you plan to use it outdoors for long hours you will be going down the same road I went down 7 years ago.
I think you will suffer from readability under sunlight and poor battery life.
Perhaps you will replace it with a MIP LCD.

I am working on accommodating the new MIP display, which has vertical resolutions, so I will be merging your code over time. I'll be thinking about whether to have a Vertical flag like your code or simply identify it by W and H as I originally thought.

**Comment by McJackson164** [comment]
Yes, i will use it outdoors. A MIP display sounds reasonable.

Okay, great!

**Comment by hishizuka** [comment]
Tell me the connection pin between TFT and A.
Others can not run your code.

**Comment by McJackson164** [comment]
ST7789_Breakout_Circuit

Are there any thrown errors/warnings? Maybe i can help

**Comment by hishizuka** [comment]
Hi, @McJackson164 

Sorry, when I try to implement the vertical layout feature, I can't incorporate all of your PRs because your and my implementation policies are very different. (Lack of consideration when resizing, i.e., cannot support different resolutions).

st7789_breakout_display.py is available for import, so please PR this source only.

**Pull request closed without merging**
