### PR TITLE
Fix rfkill commands

### PR DESCRIPTION
**Pull request by Ptosiek**
1. move detect_network
2. no need for global for Ip address
3. comment wifi/bt  n 'python'
4. Fix rfkill command

These are the 'safe' changes from #37 (that do not change the logic to check for IS_RASPI and still uses rfkill for both BT and WiFi).
Btw, the rfkill commands were not working for me, they have to be ran as sudo on the Pi for and the devices are under "rfkilldevices" key and not "", not sure why?
Also I kept the comment/uncomment scripts since there some commands for GPSD but it's not clear why it's there in the first place

### CODE REVIEW

**Comment by hishizuka** [comment]
Hi @Ptosiek ,
thank you for your PR.

Is the output of rfkill different from my environment (Raspberry Pi OS)?

An example of rfkill output in Raspberry Pi OS Bullseye is
```
{
   "": [
      {"id":0, "type":"wlan", "device":"phy0", "soft":"unblocked", "hard":"unblocked"},
      {"id":1, "type":"bluetooth", "device":"hci0", "soft":"unblocked", "hard":"unblocked"}
   ]
}
```

and, python output is
```
{'': [{'id': 0, 'type': 'wlan', 'device': 'phy0', 'soft': 'unblocked', 'hard': 'unblocked'}, {'id': 1, 'type': 'bluetooth', 'device': 'hci0', 'soft': 'unblocked', 'hard': 'unblocked'}]}
```

So, the first json key is "" not "rfkilldevices". I don't know why.
If different environments are to be considered, it may be better to have multiple key searches.

**Comment by hishizuka** [comment]
comment_out.sh and uncomment.sh are still needed.
It's a tricky specification of the Raspberry Pi, if you turn Bluetooth off, the UART path to access GPS changes from /dev/ttyS0 to /dev/ttyAMA0. So /boot/config.txt and /etc/default/gpsd must be changed at the same time.
https://www.raspberrypi.com/documentation/computers/configuration.html#primary-and-secondary-uart

I see that function execution with arguments to show_dialog can be done in PARTIAL, thanks.

**Comment by hishizuka** [comment]
So, after fixing the key for rfkill, let's move on.

**Comment by Ptosiek** [comment]
Yes using bookworm (DietPi 8.22) here.
```
Coding in hardware_wifi_bt.
It's a tricky specification of the Raspberry Pi, if you turn Bluetooth off, the UART path to access GPS changes from /dev/ttyS0 to /dev/ttyAMA0. So /boot/config.txt and /etc/default/gpsd must be changed at the same time.
```

Ok then, I'll move the rest of the comment/uncomment script in the python function then

**Pull request merged**
